[packages.pacman]
type = "packages"
sudo_cmd = "doas"
packages = [
"aarch64-linux-gnu-binutils",
"adobe-source-han-sans-otc-fonts",
"adobe-source-han-serif-otc-fonts",
"adobe-source-sans-fonts",
"alacritty",
"alsa-utils",
"arandr",
"arm-none-eabi-newlib",
"arp-scan",
"asciidoc",
"aspell-de",
"aspell-en",
"autoconf",
"automake",
"awesome",
"base",
"bash",
"bear",
"biber",
"binutils",
"bison",
"bitwarden",
"blueman",
"bluez-utils",
"bspwm",
"btop",
"ccls",
"chafa",
"chntpw",
"chrpath",
"cmake",
"coq",
"coqide",
"cpupower",
"ctags",
"cups",
"cups-pdf",
"dash",
"datamash",
"dhcpcd",
"dialog",
"discord",
"dosfstools",
"dunst",
"dzen2",
"efibootmgr",
"entr",
"evince",
"exa",
"fakeroot",
"figlet",
"file",
"findutils",
"firefox",
"flex",
"fzf",
"gawk",
"gcc",
"gcr",
"gdb",
"geckodriver",
"gettext",
"ghc",
"git",
"gnome-keyring",
"gnuplot",
"go",
"go-tools",
"gparted",
"gptfdisk",
"grc",
"grep",
"groff",
"gst-libav",
"gst-plugin-gtk",
"gst-plugins-bad",
"gst-plugins-base",
"gst-plugins-good",
"gst-plugins-ugly",
"gtk3",
"gvim",
"gzip",
"herbstluftwm",
"hexedit",
"highlight",
"htop",
"hunspell-de",
"hunspell-en_us",
"inkscape",
"inotify-tools",
"intel-ucode",
"iptables-nft",
"ispell",
"j4-dmenu-desktop",
"java-openjfx",
"jdk-openjdk",
"jdk8-openjdk",
"jq",
"jupyterlab",
"kde-gtk-config",
"kscreen",
"lib32-libcups",
"lib32-libcurl-compat",
"lib32-mesa",
"lib32-openal",
"libconfig",
"libexif",
"libkeybinder3",
"libreoffice-still",
"libtool",
"libxft",
"libxinerama",
"linux",
"linux-firmware",
"linux-lts",
"linux-lts-headers",
"lolcat",
"lrzsz",
"lsw",
"ltrace",
"luit",
"lxappearance-gtk3",
"m4",
"maim",
"make",
"man-db",
"man-pages",
"man2html",
"mdcat",
"mesa-demos",
"moreutils",
"muparser",
"neofetch",
"neovim",
"netctl",
"nlohmann-json",
"nodejs",
"ntfs-3g",
"nvidia",
"nvidia-lts",
"nvidia-prime",
"obs-studio",
"odt2txt",
"okular",
"onefetch",
"openbsd-netcat",
"optipng",
"otf-fira-mono",
"p7zip",
"pacman",
"pacman-contrib",
"pamixer",
"patch",
"pavucontrol",
"pcmanfm-gtk3",
"pdfpc",
"pdftk",
"perf",
"perl-file-mimeinfo",
"perl-image-exiftool",
"picocom",
"picom",
"pkgconf",
"plasma-desktop",
"playerctl",
"polkit-gnome",
"polybar",
"powertop",
"progress",
"pslist",
"pulseaudio",
"pulseaudio-alsa",
"pulseaudio-bluetooth",
"pulsemixer",
"python",
"python-dulwich",
"python-gitlab",
"python-matplotlib",
"python-pandas",
"python-pip",
"python-pwntools",
"python-pywal",
"python-sh",
"rbw",
"ripgrep",
"rofi",
"rsync",
"sassc",
"screen",
"scrot",
"sdl2_image",
"seahorse",
"sed",
"simple-scan",
"sshfs",
"starship",
"steam",
"strace",
"sudo",
"swi-prolog",
"sxhkd",
"synapse",
"system-config-printer",
"telegram-desktop",
"texi2html",
"texinfo",
"texlab",
"thunderbird",
"tk",
"tlp",
"tmux",
"traceroute",
"ttf-fira-code",
"ttf-fira-mono",
"ttf-hack",
"ttf-jetbrains-mono",
"ttf-liberation",
"ttf-opensans",
"ttf-ubuntu-font-family",
"uboot-tools",
"udiskie",
"ueberzug",
"unrar",
"unzip",
"up",
"usbutils",
"valgrind",
"virtualbox",
"w3m",
"webkit2gtk",
"wget",
"which",
"wine",
"wine-mono",
"wireshark-qt",
"wmctrl",
"wmname",
"wpa_supplicant",
"xclip",
"xdelta3",
"xdo",
"xdotool",
"xf86-video-intel",
"xf86-video-vesa",
"xorg-bdftopcf",
"xorg-docs",
"xorg-font-util",
"xorg-fonts-100dpi",
"xorg-fonts-75dpi",
"xorg-fonts-encodings",
"xorg-iceauth",
"xorg-mkfontscale",
"xorg-server",
"xorg-server-devel",
"xorg-server-xephyr",
"xorg-server-xnest",
"xorg-server-xvfb",
"xorg-sessreg",
"xorg-smproxy",
"xorg-x11perf",
"xorg-xcmsdb",
"xorg-xcursorgen",
"xorg-xdpyinfo",
"xorg-xdriinfo",
"xorg-xev",
"xorg-xgamma",
"xorg-xhost",
"xorg-xinit",
"xorg-xinput",
"xorg-xkbevd",
"xorg-xkbutils",
"xorg-xkill",
"xorg-xlsatoms",
"xorg-xlsclients",
"xorg-xman",
"xorg-xpr",
"xorg-xprop",
"xorg-xrandr",
"xorg-xrefresh",
"xorg-xset",
"xorg-xsetroot",
"xorg-xvinfo",
"xorg-xwayland",
"xorg-xwd",
"xorg-xwininfo",
"xorg-xwud",
"xournalpp",
"xss-lock",
"xwallpaper",
"yarn",
"youtube-dl",
"zathura",
"zathura-pdf-poppler",
"zeitgeist",
"zip",
"zsh",
]
groups=["xorg", "texlive", "texlive-lang"]
blacklist=["xorg-xbacklight"]

